import { createSlice, PayloadAction } from '@reduxjs/toolkit'

interface Info {
  id: number
  name: string
  gost: string
  size: string
  material: string
  count: string
  date: string
  number: string
  status: string
}

interface OrdersState {
  ordersData: Info[]
}

const initialState: OrdersState = {
  ordersData: [
    {
      id: 1,
      name: 'Фанера',
      gost: 'AAA-100',
      size: '300см',
      material: 'Дерево',
      count: '13',
      date: '10-02-2023',
      number: '1',
      status: 'В сборке',
    },
    {
      id: 2,
      name: 'Цемент',
      gost: 'BBB-200',
      size: '25кг',
      material: 'Цемент',
      count: '500',
      date: '10-02-2023',
      number: '1',
      status: 'В сборке',
    },
    {
      id: 3,
      name: 'Керамические блоки',
      gost: 'CCC-300',
      size: '25x25x50см',
      material: 'Керамика',
      count: '1000',
      date: '10-02-2023',
      number: '1',
      status: 'В сборке',
    },
    {
      id: 4,
      name: 'Кирпич',
      gost: 'DDD-400',
      size: '25x12x6см',
      material: 'Глина',
      count: '800',
      date: '10-02-2023',
      number: '1',
      status: 'В сборке',
    },
    {
      id: 5,
      name: 'Доски обрезные',
      gost: 'EEE-500',
      size: '50x150мм',
      material: 'Дерево',
      count: '200',
      date: '10-02-2023',
      number: '1',
      status: 'В сборке',
    },
    {
      id: 6,
      name: 'Строительный кирпич',
      gost: 'FFF-600',
      size: '25x12x6см',
      material: 'Глина',
      count: '600',
      date: '10-02-2023',
      number: '2',
      status: 'В пути',
    },
    {
      id: 7,
      name: 'Сайдинг',
      gost: 'GGG-700',
      size: '50см',
      material: 'Пластик',
      count: '100',
      date: '11-02-2023',
      number: '2',
      status: 'В пути',
    },
    {
      id: 8,
      name: 'Кровельный материал',
      gost: 'HHH-800',
      size: '1м2',
      material: 'Металл',
      count: '300',
      date: '11-02-2023',
      number: '2',
      status: 'В пути',
    },
    {
      id: 9,
      name: 'Арматура',
      gost: 'III-900',
      size: '10мм',
      material: 'Сталь',
      count: '500',
      date: '11-02-2023',
      number: '2',
      status: 'В пути',
    },
    {
      id: 10,
      name: 'Гипсовая плита',
      gost: 'JJJ-1000',
      size: '2x1м',
      material: 'Гипс',
      count: '100',
      date: '11-02-2023',
      number: '2',
      status: 'В пути',
    },
    {
      id: 11,
      name: 'Бетон',
      gost: 'KKK-1100',
      size: '1куб. м',
      material: 'Бетон',
      count: '50',
      date: '12-02-2023',
      number: '3',
      status: 'В пути',
    },
    {
      id: 12,
      name: 'Газобетонные блоки',
      gost: 'LLL-1200',
      size: '60x30x20см',
      material: 'Газобетон',
      count: '300',
      date: '12-02-2023',
      number: '3',
      status: 'В пути',
    },
    {
      id: 13,
      name: 'Кровельные листы',
      gost: 'MMM-1300',
      size: '2м',
      material: 'Металл',
      count: '1000',
      date: '12-02-2023',
      number: '3',
      status: 'В пути',
    },
    {
      id: 14,
      name: 'Песок',
      gost: 'NNN-1400',
      size: '1т',
      material: 'Песок',
      count: '600',
      date: '12-02-2023',
      number: '3',
      status: 'В пути',
    },
    {
      id: 15,
      name: 'Известь',
      gost: 'OOO-1500',
      size: '25кг',
      material: 'Известь',
      count: '200',
      date: '12-02-2023',
      number: '3',
      status: 'В пути',
    },
    {
      id: 16,
      name: 'Металлические конструкции',
      gost: 'PPP-1600',
      size: '3м',
      material: 'Металл',
      count: '50',
      date: '13-02-2023',
      number: '4',
      status: 'В пути',
    },
    {
      id: 17,
      name: 'Полиуретановая пена',
      gost: 'QQQ-1700',
      size: '750мл',
      material: 'Полиуретан',
      count: '100',
      date: '13-02-2023',
      number: '4',
      status: 'В пути',
    },
    {
      id: 18,
      name: 'Керамическая плитка',
      gost: 'RRR-1800',
      size: '30x30см',
      material: 'Керамика',
      count: '400',
      date: '13-02-2023',
      number: '4',
      status: 'В пути',
    },
    {
      id: 19,
      name: 'Стекло',
      gost: 'SSS-1900',
      size: '3м2',
      material: 'Стекло',
      count: '50',
      date: '13-02-2023',
      number: '4',
      status: 'В пути',
    },
    {
      id: 20,
      name: 'Камень',
      gost: 'TTT-2000',
      size: '20x20см',
      material: 'Камень',
      count: '150',
      date: '13-02-2023',
      number: '4',
      status: 'В пути',
    },
    {
      id: 21,
      name: 'Керамические панели',
      gost: 'UUU-2100',
      size: '30x60см',
      material: 'Керамика',
      count: '300',
      date: '14-02-2023',
      number: '5',
      status: 'Доставлен',
    },
    {
      id: 22,
      name: 'Керамогранит',
      gost: 'VVV-2200',
      size: '40x40см',
      material: 'Керамика',
      count: '200',
      date: '14-02-2023',
      number: '5',
      status: 'Доставлен',
    },
    {
      id: 23,
      name: 'Древесно-стружечные плиты',
      gost: 'WWW-2300',
      size: '250x125см',
      material: 'Древесина',
      count: '100',
      date: '14-02-2023',
      number: '5',
      status: 'Доставлен',
    },
    {
      id: 24,
      name: 'Акриловые ванны',
      gost: 'XXX-2400',
      size: '170x70см',
      material: 'Акрил',
      count: '50',
      date: '14-02-2023',
      number: '5',
      status: 'Доставлен',
    },
    {
      id: 25,
      name: 'Керамические трубы',
      gost: 'YYY-2500',
      size: '40мм',
      material: 'Керамика',
      count: '500',
      date: '14-02-2023',
      number: '5',
      status: 'Доставлен',
    },
    {
      id: 26,
      name: 'Поликарбонатные листы',
      gost: 'ZZZ-2600',
      size: '2м',
      material: 'Поликарбонат',
      count: '100',
      date: '15-02-2023',
      number: '6',
      status: 'Доставлен',
    },
    {
      id: 27,
      name: 'Минеральная вата',
      gost: 'AAA-2700',
      size: '120x60см',
      material: 'Минеральная вата',
      count: '200',
      date: '15-02-2023',
      number: '6',
      status: 'Доставлен',
    },
    {
      id: 28,
      name: 'Канализационные трубы',
      gost: 'BBB-2800',
      size: '110мм',
      material: 'Пластик',
      count: '300',
      date: '15-02-2023',
      number: '6',
      status: 'Доставлен',
    },
    {
      id: 29,
      name: 'Керамические уголки',
      gost: 'CCC-2900',
      size: '2x2см',
      material: 'Керамика',
      count: '400',
      date: '15-02-2023',
      number: '6',
      status: 'Доставлен',
    },
    {
      id: 30,
      name: 'Гипсокартонные листы',
      gost: 'DDD-3000',
      size: '250x120см',
      material: 'Гипсокартон',
      count: '100',
      date: '15-02-2023',
      number: '6',
      status: 'Доставлен',
    },
    {
      id: 31,
      name: 'Штукатурка',
      gost: 'EEE-3100',
      size: '25кг',
      material: 'Штукатурка',
      count: '200',
      date: '16-02-2023',
      number: '7',
      status: 'Доставлен',
    },
    {
      id: 32,
      name: 'Фильтр для воды',
      gost: 'FFF-3200',
      size: '10дюймов',
      material: 'Пластик',
      count: '400',
      date: '16-02-2023',
      number: '7',
      status: 'Доставлен',
    },
    {
      id: 33,
      name: 'Шифер',
      gost: 'GGG-3300',
      size: '200x110см',
      material: 'Асбестоцементный материал',
      count: '100',
      date: '16-02-2023',
      number: '7',
      status: 'Доставлен',
    },
    {
      id: 34,
      name: 'Трубы ПЭ для водоснабжения',
      gost: 'HHH-3400',
      size: '50мм',
      material: 'Полиэтилен',
      count: '300',
      date: '16-02-2023',
      number: '7',
      status: 'Доставлен',
    },
    {
      id: 35,
      name: 'Профиль маячковый',
      gost: 'III-3500',
      size: '2м',
      material: 'Металл',
      count: '200',
      date: '16-02-2023',
      number: '7',
      status: 'Доставлен',
    },
    {
      id: 36,
      name: 'Смотровые люки',
      gost: 'JJJ-3600',
      size: '60x60см',
      material: 'Металл',
      count: '10',
      date: '16-02-2023',
      number: '7',
      status: 'Доставлен',
    },
    {
      id: 37,
      name: 'Пластиковые окна',
      gost: 'KKK-3700',
      size: '120x80см',
      material: 'Пластик',
      count: '50',
      date: '17-02-2023',
      number: '8',
      status: 'Доставлен',
    },
    {
      id: 38,
      name: 'Фанера',
      gost: 'LLL-3800',
      size: '2440x1220мм',
      material: 'Фанера',
      count: '100',
      date: '17-02-2023',
      number: '8',
      status: 'Доставлен',
    },
    {
      id: 39,
      name: 'Кормушка для птиц',
      gost: 'MMM-3900',
      size: '50x50см',
      material: 'Дерево',
      count: '200',
      date: '17-02-2023',
      number: '8',
      status: 'Доставлен',
    },
    {
      id: 40,
      name: 'Стеновые панели',
      gost: 'NNN-4000',
      size: '120x60см',
      material: 'Дерево',
      count: '300',
      date: '17-02-2023',
      number: '8',
      status: 'Доставлен',
    },
    {
      id: 41,
      name: 'Кабельные каналы',
      gost: 'OOO-4100',
      size: '40x25мм',
      material: 'Пластик',
      count: '200',
      date: '18-02-2023',
      number: '9',
      status: 'Доставлен',
    },
    {
      id: 42,
      name: 'Гвозди',
      gost: 'PPP-4200',
      size: '2.0x25мм',
      material: 'Металл',
      count: '500',
      date: '18-02-2023',
      number: '9',
      status: 'Доставлен',
    },
    {
      id: 43,
      name: 'Шпатлевка для стен',
      gost: 'QQQ-4300',
      size: '5кг',
      material: 'Шпатлевка',
      count: '100',
      date: '18-02-2023',
      number: '9',
      status: 'Доставлен',
    },
    {
      id: 44,
      name: 'Керамические плитки',
      gost: 'RRR-4400',
      size: '20x20см',
      material: 'Керамика',
      count: '400',
      date: '18-02-2023',
      number: '9',
      status: 'Доставлен',
    },
    {
      id: 45,
      name: 'Металлические двери',
      gost: 'SSS-4500',
      size: '200x80см',
      material: 'Металл',
      count: '50',
      date: '18-02-2023',
      number: '9',
      status: 'Доставлен',
    },
    {
      id: 46,
      name: 'Ламинат',
      gost: 'TTT-4600',
      size: '120x19см',
      material: 'Ламинат',
      count: '100',
      date: '19-02-2023',
      number: '10',
      status: 'Доставлен',
    },
    {
      id: 47,
      name: 'Стеклопакеты',
      gost: 'UUU-4700',
      size: '120x80см',
      material: 'Стекло',
      count: '50',
      date: '19-02-2023',
      number: '10',
      status: 'Доставлен',
    },
    {
      id: 48,
      name: 'Металлические профили',
      gost: 'VVV-4800',
      size: '3м',
      material: 'Металл',
      count: '100',
      date: '19-02-2023',
      number: '10',
      status: 'Доставлен',
    },
    {
      id: 49,
      name: 'Вентиляционные решетки',
      gost: 'WWW-4900',
      size: '30x30см',
      material: 'Металл',
      count: '200',
      date: '19-02-2023',
      number: '10',
      status: 'Доставлен',
    },
    {
      id: 50,
      name: 'Фильтры для кондиционеров',
      gost: 'XXX-5000',
      size: '40x20см',
      material: 'Фильтрующий материал',
      count: '300',
      date: '19-02-2023',
      number: '10',
      status: 'Доставлен',
    },
    {
      id: 51,
      name: 'Крышки канализационные',
      gost: 'YYY-5100',
      size: '40x40см',
      material: 'Пластик',
      count: '150',
      date: '20-02-2023',
      number: '11',
      status: 'Доставлен',
    },
    {
      id: 52,
      name: 'Пленка для упаковки',
      gost: 'ZZZ-5200',
      size: '1000x500см',
      material: 'Пленка',
      count: '50',
      date: '20-02-2023',
      number: '11',
      status: 'Доставлен',
    },
    {
      id: 53,
      name: 'Шланг для полива',
      gost: 'AAA-5300',
      size: '25м',
      material: 'Полимер',
      count: '100',
      date: '20-02-2023',
      number: '11',
      status: 'Доставлен',
    },
    {
      id: 54,
      name: 'Рулонные шторы',
      gost: 'BBB-5400',
      size: '200x150см',
      material: 'Ткань',
      count: '20',
      date: '20-02-2023',
      number: '11',
      status: 'Доставлен',
    },
    {
      id: 55,
      name: 'Теплоизоляционные маты',
      gost: 'CCC-5500',
      size: '120x60см',
      material: 'Минеральная вата',
      count: '100',
      date: '20-02-2023',
      number: '11',
      status: 'Доставлен',
    },
    {
      id: 56,
      name: 'Потолочные панели',
      gost: 'DDD-5600',
      size: '120x30см',
      material: 'ПВХ',
      count: '200',
      date: '21-02-2023',
      number: '12',
      status: 'Доставлен',
    },
    {
      id: 57,
      name: 'Сайдинг',
      gost: 'EEE-5700',
      size: '366x15см',
      material: 'Металлопластик',
      count: '150',
      date: '21-02-2023',
      number: '12',
      status: 'Доставлен',
    },
    {
      id: 58,
      name: 'Керамический гранит',
      gost: 'FFF-5800',
      size: '60x60см',
      material: 'Керамика',
      count: '100',
      date: '21-02-2023',
      number: '12',
      status: 'Доставлен',
    },
    {
      id: 59,
      name: 'Листовая сталь',
      gost: 'GGG-5900',
      size: '2мм',
      material: 'Металл',
      count: '50',
      date: '21-02-2023',
      number: '12',
      status: 'Доставлен',
    },
    {
      id: 60,
      name: 'Трубы полипропиленовые',
      gost: 'HHH-6000',
      size: '25мм',
      material: 'Полипропилен',
      count: '300',
      date: '22-02-2023',
      number: '13',
      status: 'Доставлен',
    },
    {
      id: 61,
      name: 'Фанерные листы',
      gost: 'III-6100',
      size: '1525x1525мм',
      material: 'Фанера',
      count: '100',
      date: '22-02-2023',
      number: '13',
      status: 'Доставлен',
    },
    {
      id: 62,
      name: 'Коврики для ванной',
      gost: 'JJJ-6200',
      size: '50x70см',
      material: 'Резина',
      count: '200',
      date: '22-02-2023',
      number: '13',
      status: 'Доставлен',
    },
    {
      id: 63,
      name: 'Кирпич облицовочный',
      gost: 'KKK-6300',
      size: '250x120x65мм',
      material: 'Керамика',
      count: '500',
      date: '22-02-2023',
      number: '13',
      status: 'Доставлен',
    },
    {
      id: 64,
      name: 'Светильники',
      gost: 'LLL-6400',
      size: '20x20см',
      material: 'Металл',
      count: '100',
      date: '22-02-2023',
      number: '13',
      status: 'Доставлен',
    },
    {
      id: 65,
      name: 'Сухие строительные смеси',
      gost: 'MMM-6500',
      size: '25кг',
      material: 'Смесь',
      count: '50',
      date: '23-02-2023',
      number: '14',
      status: 'Доставлен',
    },
    {
      id: 56,
      name: 'Потолочные панели',
      gost: 'DDD-5600',
      size: '120x30см',
      material: 'ПВХ',
      count: '200',
      date: '21-02-2023',
      number: '12',
      status: 'Доставлен',
    },
    {
      id: 57,
      name: 'Сайдинг',
      gost: 'EEE-5700',
      size: '366x15см',
      material: 'Металлопластик',
      count: '150',
      date: '21-02-2023',
      number: '12',
      status: 'Доставлен',
    },
    {
      id: 58,
      name: 'Керамический гранит',
      gost: 'FFF-5800',
      size: '60x60см',
      material: 'Керамика',
      count: '100',
      date: '21-02-2023',
      number: '12',
      status: 'Доставлен',
    },
    {
      id: 59,
      name: 'Листовая сталь',
      gost: 'GGG-5900',
      size: '2мм',
      material: 'Металл',
      count: '50',
      date: '21-02-2023',
      number: '12',
      status: 'Доставлен',
    },
    {
      id: 60,
      name: 'Трубы полипропиленовые',
      gost: 'HHH-6000',
      size: '25мм',
      material: 'Полипропилен',
      count: '300',
      date: '27-02-2023',
      number: '13',
      status: 'Доставлен',
    },
    {
      id: 61,
      name: 'Фанерные листы',
      gost: 'III-6100',
      size: '1525x1525мм',
      material: 'Фанера',
      count: '100',
      date: '27-02-2023',
      number: '13',
      status: 'Доставлен',
    },
    {
      id: 62,
      name: 'Коврики для ванной',
      gost: 'JJJ-6200',
      size: '50x70см',
      material: 'Резина',
      count: '200',
      date: '27-02-2023',
      number: '13',
      status: 'Доставлен',
    },
    {
      id: 63,
      name: 'Кирпич облицовочный',
      gost: 'KKK-6300',
      size: '250x120x65мм',
      material: 'Керамика',
      count: '500',
      date: '27-02-2023',
      number: '13',
      status: 'Доставлен',
    },
    {
      id: 64,
      name: 'Светильники',
      gost: 'LLL-6400',
      size: '20x20см',
      material: 'Металл',
      count: '100',
      date: '27-02-2023',
      number: '13',
      status: 'Доставлен',
    },
    {
      id: 65,
      name: 'Сухие строительные смеси',
      gost: 'MMM-6500',
      size: '25кг',
      material: 'Смесь',
      count: '50',
      date: '28-02-2023',
      number: '14',
      status: 'Доставлен',
    },
    {
      id: 66,
      name: 'Пеноплекс',
      gost: 'NNN-6600',
      size: '100x70x5см',
      material: 'Пенополистирол',
      count: '300',
      date: '28-02-2023',
      number: '14',
      status: 'Доставлен',
    },
    {
      id: 67,
      name: 'Гвозди строительные',
      gost: 'OOO-6700',
      size: '6x120мм',
      material: 'Сталь',
      count: '500',
      date: '28-02-2023',
      number: '14',
      status: 'Доставлен',
    },
    {
      id: 68,
      name: 'Сантехнические краны',
      gost: 'PPP-6800',
      size: '1/2 дюйма',
      material: 'Латунь',
      count: '100',
      date: '28-02-2023',
      number: '14',
      status: 'Доставлен',
    },
    {
      id: 69,
      name: 'Ламинат',
      gost: 'QQQ-6900',
      size: '1285x192x10мм',
      material: 'Древесина',
      count: '200',
      date: '28-02-2023',
      number: '14',
      status: 'Доставлен',
    },
    {
      id: 70,
      name: 'Плитка керамическая',
      gost: 'RRR-7000',
      size: '100x100мм',
      material: 'Керамика',
      count: '400',
      date: '28-02-2023',
      number: '14',
      status: 'Доставлен',
    },
    {
      id: 71,
      name: 'Смеситель для ванны',
      gost: 'SSS-7100',
      size: '55x15см',
      material: 'Латунь',
      count: '50',
      date: '29-02-2023',
      number: '15',
      status: 'Доставлен',
    },
    {
      id: 72,
      name: 'Кабель электрический',
      gost: 'TTT-7200',
      size: '3x1,5 мм²',
      material: 'Медь',
      count: '1000',
      date: '29-02-2023',
      number: '15',
      status: 'Доставлен',
    },
    {
      id: 73,
      name: 'Кондиционер',
      gost: 'UUU-7300',
      size: '9000 BTU',
      material: 'Пластик',
      count: '20',
      date: '29-02-2023',
      number: '15',
      status: 'Доставлен',
    },
    {
      id: 74,
      name: 'Двери входные металлические',
      gost: 'VVV-7400',
      size: '900x2000мм',
      material: 'Металл',
      count: '10',
      date: '29-02-2023',
      number: '15',
      status: 'Доставлен',
    },
    {
      id: 75,
      name: 'Теплоизоляционные плиты',
      gost: 'WWW-7500',
      size: '1000x500мм',
      material: 'Пенополистирол',
      count: '100',
      date: '29-02-2023',
      number: '15',
      status: 'Доставлен',
    },
    {
      id: 76,
      name: 'Сухие смеси для штукатурки',
      gost: 'XXX-7600',
      size: '30кг',
      material: 'Смесь',
      count: '50',
      date: '29-02-2023',
      number: '15',
      status: 'Доставлен',
    },
    {
      id: 77,
      name: 'Шурупы строительные',
      gost: 'YYY-7700',
      size: '5x60мм',
      material: 'Сталь',
      count: '1000',
      date: '30-02-2023',
      number: '16',
      status: 'Доставлен',
    },
    {
      id: 78,
      name: 'Гипсокартон',
      gost: 'ZZZ-7800',
      size: '2500x1200x12,5мм',
      material: 'Гипс',
      count: '100',
      date: '30-02-2023',
      number: '16',
      status: 'Доставлен',
    },
    {
      id: 79,
      name: 'Плинтус',
      gost: 'AAA-7900',
      size: '50x10мм',
      material: 'Дерево',
      count: '200',
      date: '30-02-2023',
      number: '16',
      status: 'Доставлен',
    },
    {
      id: 80,
      name: 'Фурнитура для дверей',
      gost: 'BBB-8000',
      size: '15x10см',
      material: 'Металл',
      count: '50',
      date: '30-02-2023',
      number: '16',
      status: 'Доставлен',
    },
    {
      id: 81,
      name: 'Изоляционная лента',
      gost: 'CCC-8100',
      size: '5см',
      material: 'ПВХ',
      count: '200',
      date: '30-02-2023',
      number: '16',
      status: 'Доставлен',
    },
    {
      id: 82,
      name: 'Трубы металлические',
      gost: 'DDD-8200',
      size: '1 дюйм',
      material: 'Металл',
      count: '100',
      date: '01-03-2023',
      number: '17',
      status: 'Доставлен',
    },
    {
      id: 83,
      name: 'Системы капельного полива',
      gost: 'EEE-8300',
      size: '25м',
      material: 'Пластик',
      count: '10',
      date: '01-03-2023',
      number: '17',
      status: 'Доставлен',
    },
    {
      id: 84,
      name: 'Смеситель для кухни',
      gost: 'FFF-8400',
      size: '30x15см',
      material: 'Латунь',
      count: '30',
      date: '01-03-2023',
      number: '17',
      status: 'Доставлен',
    },
    {
      id: 85,
      name: 'Экран для ванной',
      gost: 'GGG-8500',
      size: '140x140см',
      material: 'Полиэстер',
      count: '20',
      date: '01-03-2023',
      number: '17',
      status: 'Доставлен',
    },
    {
      id: 86,
      name: 'Крепежные элементы',
      gost: 'HHH-8600',
      size: '8x40мм',
      material: 'Металл',
      count: '500',
      date: '01-03-2023',
      number: '17',
      status: 'Доставлен',
    },
    {
      id: 87,
      name: 'Профиль направляющий',
      gost: 'III-8700',
      size: '3000x40x40мм',
      material: 'Металл',
      count: '50',
      date: '01-03-2023',
      number: '17',
      status: 'Доставлен',
    },
    {
      id: 88,
      name: 'Лента малярная',
      gost: 'JJJ-8800',
      size: '50мм',
      material: 'Бумага',
      count: '100',
      date: '01-03-2023',
      number: '17',
      status: 'Доставлен',
    },
    {
      id: 89,
      name: 'Керамическая плитка',
      gost: 'KKK-8900',
      size: '200x200мм',
      material: 'Керамика',
      count: '300',
      date: '01-03-2023',
      number: '18',
      status: 'Доставлен',
    },
    {
      id: 90,
      name: 'Кладочный раствор',
      gost: 'LLL-9000',
      size: '50кг',
      material: 'Смесь',
      count: '40',
      date: '02-03-2023',
      number: '18',
      status: 'Доставлен',
    },
    {
      id: 91,
      name: 'Сверла по металлу',
      gost: 'MMM-9100',
      size: '6мм',
      material: 'Сталь',
      count: '50',
      date: '02-03-2023',
      number: '18',
      status: 'Доставлен',
    },
    {
      id: 92,
      name: 'Шина грузовая',
      gost: 'NNN-9200',
      size: '5000x200x100мм',
      material: 'Металл',
      count: '5',
      date: '02-03-2023',
      number: '18',
      status: 'Доставлен',
    },
    {
      id: 93,
      name: 'Круг отрезной по металлу',
      gost: 'OOO-9300',
      size: '125мм',
      material: 'Абразив',
      count: '20',
      date: '02-03-2023',
      number: '18',
      status: 'Доставлен',
    },
    {
      id: 94,
      name: 'Рулон резиновой кровли',
      gost: 'PPP-9400',
      size: '1200x20000мм',
      material: 'Резина',
      count: '10',
      date: '03-03-2023',
      number: '19',
      status: 'Доставлен',
    },
    {
      id: 95,
      name: 'Лист гофрированный',
      gost: 'QQQ-9500',
      size: '1250x2500мм',
      material: 'Сталь',
      count: '30',
      date: '03-03-2023',
      number: '19',
      status: 'Доставлен',
    },
    {
      id: 96,
      name: 'Кирпич облицовочный',
      gost: 'RRR-9600',
      size: '250x120x65мм',
      material: 'Керамика',
      count: '200',
      date: '03-03-2023',
      number: '19',
      status: 'Доставлен',
    },
    {
      id: 97,
      name: 'Система водоотведения',
      gost: 'SSS-9700',
      size: '100х100мм',
      material: 'Пластик',
      count: '20',
      date: '03-03-2023',
      number: '19',
      status: 'Доставлен',
    },
    {
      id: 98,
      name: 'Люстра потолочная',
      gost: 'TTT-9800',
      size: '50х50см',
      material: 'Стекло',
      count: '5',
      date: '03-03-2023',
      number: '19',
      status: 'Доставлен',
    },
    {
      id: 99,
      name: 'Мебель для гостиной',
      gost: 'UUU-9900',
      size: '200x200x50см',
      material: 'Дерево',
      count: '2',
      date: '03-03-2023',
      number: '19',
      status: 'Доставлен',
    },
    {
      id: 100,
      name: 'Краска для стен и потолков',
      gost: 'VVV-10000',
      size: '10л',
      material: 'Краска',
      count: '10',
      date: '03-03-2023',
      number: '19',
      status: 'Доставлен',
    },
    {
      id: 101,
      name: 'Система вентиляции',
      gost: 'WWW-10100',
      size: '300х300мм',
      material: 'Пластик',
      count: '10',
      date: '05-03-2023',
      number: '20',
      status: 'Доставлен',
    },
    {
      id: 102,
      name: 'Радиатор отопления',
      gost: 'XXX-10200',
      size: '500х500мм',
      material: 'Металл',
      count: '4',
      date: '05-03-2023',
      number: '20',
      status: 'Доставлен',
    },
    {
      id: 103,
      name: 'Термостат для отопления',
      gost: 'YYY-10300',
      size: '10x10см',
      material: 'Пластик',
      count: '5',
      date: '05-03-2023',
      number: '20',
      status: 'Доставлен',
    },
    {
      id: 104,
      name: 'Насос для воды',
      gost: 'ZZZ-10400',
      size: '200х200мм',
      material: 'Металл',
      count: '3',
      date: '05-03-2023',
      number: '20',
      status: 'Доставлен',
    },
  ],
}

const ordersDataSlice = createSlice({
  name: 'order',
  initialState,
  reducers: {
    addNewOrder: (state, action: PayloadAction<Info>) => {
      state.ordersData.push(action.payload)
    },
  },
})

export const { addNewOrder } = ordersDataSlice.actions

export default ordersDataSlice.reducer
